### ISSUE TITLE
Rename to Elmish.Remoting and publish an alpha?

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Nhowka/TestRemoting#1]
Hi @Nhowka  
This is starting to become an awesome library! why not publish an alpha to let people play around with it
> Alpha = you don't care about breaking the api 😉

**Comment by Nhowka** [comment]
Hey, @Zaid-Ajaj! It's on my plans to do it today. I have some ideas that could work so we can close https://github.com/Zaid-Ajaj/Fable.Remoting/issues/3 too.

**Comment by Nhowka** [comment]
Published from https://github.com/Nhowka/Elmish.Remoting

**Comment by Zaid-Ajaj** [comment]
Awesome! keep up the good work :smile:
